presubmits:
  - name: argocd
    run_if_changed: "(pkg/ee/default-application-catalog/|.prow/)"
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubermatic.git"
    labels:
      preset-aws-e2e-kkp: "true"
      preset-kubeconfig-ci: "true"
      preset-docker-mirror: "true"
      preset-docker-pull: "true"
      preset-docker-push: "true"
      preset-kind-volume-mounts: "true"
      preset-goproxy: "true"
      preset-e2e-ssh: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.23-node-20-kind-0.24-4
          command:
            - "./hack/ci/run-default-application-e2e-test.sh"
          args:
            - "--application-name"
            - "argocd"
          env:
            - name: KUBERMATIC_EDITION
              value: ee
            - name: SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: e2e-ci
                  key: serviceAccountSigningKey
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 14Gi
              cpu: 4
            limits:
              memory: 18Gi

  - name: cert-manager
    run_if_changed: "(pkg/ee/default-application-catalog/|.prow/)"
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubermatic.git"
    labels:
      preset-aws-e2e-kkp: "true"
      preset-kubeconfig-ci: "true"
      preset-docker-mirror: "true"
      preset-docker-pull: "true"
      preset-docker-push: "true"
      preset-kind-volume-mounts: "true"
      preset-goproxy: "true"
      preset-e2e-ssh: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.23-node-20-kind-0.24-4
          command:
            - "./hack/ci/run-default-application-e2e-test.sh"
          args:
            - "--application-name"
            - "cert-manager"
          env:
            - name: KUBERMATIC_EDITION
              value: ee
            - name: SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: e2e-ci
                  key: serviceAccountSigningKey
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 14Gi
              cpu: 4
            limits:
              memory: 18Gi

  - name: echoserver
    run_if_changed: "(pkg/ee/default-application-catalog/|.prow/)"
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubermatic.git"
    labels:
      preset-aws-e2e-kkp: "true"
      preset-kubeconfig-ci: "true"
      preset-docker-mirror: "true"
      preset-docker-pull: "true"
      preset-docker-push: "true"
      preset-kind-volume-mounts: "true"
      preset-goproxy: "true"
      preset-e2e-ssh: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.23-node-20-kind-0.24-4
          command:
            - "./hack/ci/run-default-application-e2e-test.sh"
          args:
            - "--application-name"
            - "echoserver"
          env:
            - name: KUBERMATIC_EDITION
              value: ee
            - name: SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: e2e-ci
                  key: serviceAccountSigningKey
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 14Gi
              cpu: 4
            limits:
              memory: 18Gi

  - name: echoserver-with-variables
    run_if_changed: "(pkg/ee/default-application-catalog/|.prow/)"
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubermatic.git"
    labels:
      preset-aws-e2e-kkp: "true"
      preset-kubeconfig-ci: "true"
      preset-docker-mirror: "true"
      preset-docker-pull: "true"
      preset-docker-push: "true"
      preset-kind-volume-mounts: "true"
      preset-goproxy: "true"
      preset-e2e-ssh: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.23-node-20-kind-0.24-4
          command:
            - "./hack/ci/run-default-application-e2e-test.sh"
          args:
            - "--application-name"
            - "echoserver-with-variables"
          env:
            - name: KUBERMATIC_EDITION
              value: ee
            - name: SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: e2e-ci
                  key: serviceAccountSigningKey
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 14Gi
              cpu: 4
            limits:
              memory: 18Gi

  - name: falco
    run_if_changed: "(pkg/ee/default-application-catalog/|.prow/)"
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubermatic.git"
    labels:
      preset-aws-e2e-kkp: "true"
      preset-kubeconfig-ci: "true"
      preset-docker-mirror: "true"
      preset-docker-pull: "true"
      preset-docker-push: "true"
      preset-kind-volume-mounts: "true"
      preset-goproxy: "true"
      preset-e2e-ssh: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.23-node-20-kind-0.24-4
          command:
            - "./hack/ci/run-default-application-e2e-test.sh"
          args:
            - "--application-name"
            - "falco"
          env:
            - name: KUBERMATIC_EDITION
              value: ee
            - name: SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: e2e-ci
                  key: serviceAccountSigningKey
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 14Gi
              cpu: 4
            limits:
              memory: 18Gi

  - name: flux
    run_if_changed: "(pkg/ee/default-application-catalog/|.prow/)"
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubermatic.git"
    labels:
      preset-aws-e2e-kkp: "true"
      preset-kubeconfig-ci: "true"
      preset-docker-mirror: "true"
      preset-docker-pull: "true"
      preset-docker-push: "true"
      preset-kind-volume-mounts: "true"
      preset-goproxy: "true"
      preset-e2e-ssh: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.23-node-20-kind-0.24-4
          command:
            - "./hack/ci/run-default-application-e2e-test.sh"
          args:
            - "--application-name"
            - "flux"
          env:
            - name: KUBERMATIC_EDITION
              value: ee
            - name: SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: e2e-ci
                  key: serviceAccountSigningKey
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 14Gi
              cpu: 4
            limits:
              memory: 18Gi

  - name: k8sgpt
    run_if_changed: "(pkg/ee/default-application-catalog/|.prow/)"
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubermatic.git"
    labels:
      preset-aws-e2e-kkp: "true"
      preset-kubeconfig-ci: "true"
      preset-docker-mirror: "true"
      preset-docker-pull: "true"
      preset-docker-push: "true"
      preset-kind-volume-mounts: "true"
      preset-goproxy: "true"
      preset-e2e-ssh: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.23-node-20-kind-0.24-4
          command:
            - "./hack/ci/run-default-application-e2e-test.sh"
          args:
            - "--application-name"
            - "k8sgpt"
          env:
            - name: KUBERMATIC_EDITION
              value: ee
            - name: SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: e2e-ci
                  key: serviceAccountSigningKey
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 14Gi
              cpu: 4
            limits:
              memory: 18Gi

  - name: kube-vip
    run_if_changed: "(pkg/ee/default-application-catalog/|.prow/)"
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubermatic.git"
    labels:
      preset-aws-e2e-kkp: "true"
      preset-kubeconfig-ci: "true"
      preset-docker-mirror: "true"
      preset-docker-pull: "true"
      preset-docker-push: "true"
      preset-kind-volume-mounts: "true"
      preset-goproxy: "true"
      preset-e2e-ssh: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.23-node-20-kind-0.24-4
          command:
            - "./hack/ci/run-default-application-e2e-test.sh"
          args:
            - "--application-name"
            - "kube-vip"
          env:
            - name: KUBERMATIC_EDITION
              value: ee
            - name: SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: e2e-ci
                  key: serviceAccountSigningKey
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 14Gi
              cpu: 4
            limits:
              memory: 18Gi

  - name: kubevirt
    run_if_changed: "(pkg/ee/default-application-catalog/|.prow/)"
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubermatic.git"
    labels:
      preset-aws-e2e-kkp: "true"
      preset-kubeconfig-ci: "true"
      preset-docker-mirror: "true"
      preset-docker-pull: "true"
      preset-docker-push: "true"
      preset-kind-volume-mounts: "true"
      preset-goproxy: "true"
      preset-e2e-ssh: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.23-node-20-kind-0.24-4
          command:
            - "./hack/ci/run-default-application-e2e-test.sh"
          args:
            - "--application-name"
            - "kubevirt"
          env:
            - name: KUBERMATIC_EDITION
              value: ee
            - name: SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: e2e-ci
                  key: serviceAccountSigningKey
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 14Gi
              cpu: 4
            limits:
              memory: 18Gi

  - name: metallb
    run_if_changed: "(pkg/ee/default-application-catalog/|.prow/)"
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubermatic.git"
    labels:
      preset-aws-e2e-kkp: "true"
      preset-kubeconfig-ci: "true"
      preset-docker-mirror: "true"
      preset-docker-pull: "true"
      preset-docker-push: "true"
      preset-kind-volume-mounts: "true"
      preset-goproxy: "true"
      preset-e2e-ssh: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.23-node-20-kind-0.24-4
          command:
            - "./hack/ci/run-default-application-e2e-test.sh"
          args:
            - "--application-name"
            - "metallb"
          env:
            - name: KUBERMATIC_EDITION
              value: ee
            - name: SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: e2e-ci
                  key: serviceAccountSigningKey
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 14Gi
              cpu: 4
            limits:
              memory: 18Gi

  - name: nginx_ingress_controller
    run_if_changed: "(pkg/ee/default-application-catalog/|.prow/)"
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubermatic.git"
    labels:
      preset-aws-e2e-kkp: "true"
      preset-kubeconfig-ci: "true"
      preset-docker-mirror: "true"
      preset-docker-pull: "true"
      preset-docker-push: "true"
      preset-kind-volume-mounts: "true"
      preset-goproxy: "true"
      preset-e2e-ssh: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.23-node-20-kind-0.24-4
          command:
            - "./hack/ci/run-default-application-e2e-test.sh"
          args:
            - "--application-name"
            - "nginx_ingress_controller"
          env:
            - name: KUBERMATIC_EDITION
              value: ee
            - name: SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: e2e-ci
                  key: serviceAccountSigningKey
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 14Gi
              cpu: 4
            limits:
              memory: 18Gi

  - name: nvidia_gpu_operator
    run_if_changed: "(pkg/ee/default-application-catalog/|.prow/)"
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubermatic.git"
    labels:
      preset-aws-e2e-kkp: "true"
      preset-kubeconfig-ci: "true"
      preset-docker-mirror: "true"
      preset-docker-pull: "true"
      preset-docker-push: "true"
      preset-kind-volume-mounts: "true"
      preset-goproxy: "true"
      preset-e2e-ssh: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.23-node-20-kind-0.24-4
          command:
            - "./hack/ci/run-default-application-e2e-test.sh"
          args:
            - "--application-name"
            - "nvidia_gpu_operator"
          env:
            - name: KUBERMATIC_EDITION
              value: ee
            - name: SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: e2e-ci
                  key: serviceAccountSigningKey
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 14Gi
              cpu: 4
            limits:
              memory: 18Gi

  - name: sealed-secrets
    run_if_changed: "(pkg/ee/default-application-catalog/|.prow/)"
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubermatic.git"
    labels:
      preset-aws-e2e-kkp: "true"
      preset-kubeconfig-ci: "true"
      preset-docker-mirror: "true"
      preset-docker-pull: "true"
      preset-docker-push: "true"
      preset-kind-volume-mounts: "true"
      preset-goproxy: "true"
      preset-e2e-ssh: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.23-node-20-kind-0.24-4
          command:
            - "./hack/ci/run-default-application-e2e-test.sh"
          args:
            - "--application-name"
            - "sealed-secrets"
          env:
            - name: KUBERMATIC_EDITION
              value: ee
            - name: SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: e2e-ci
                  key: serviceAccountSigningKey
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 14Gi
              cpu: 4
            limits:
              memory: 18Gi

  - name: trivy
    run_if_changed: "(pkg/ee/default-application-catalog/|.prow/)"
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubermatic.git"
    labels:
      preset-aws-e2e-kkp: "true"
      preset-kubeconfig-ci: "true"
      preset-docker-mirror: "true"
      preset-docker-pull: "true"
      preset-docker-push: "true"
      preset-kind-volume-mounts: "true"
      preset-goproxy: "true"
      preset-e2e-ssh: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.23-node-20-kind-0.24-4
          command:
            - "./hack/ci/run-default-application-e2e-test.sh"
          args:
            - "--application-name"
            - "trivy"
          env:
            - name: KUBERMATIC_EDITION
              value: ee
            - name: SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: e2e-ci
                  key: serviceAccountSigningKey
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 14Gi
              cpu: 4
            limits:
              memory: 18Gi

  - name: trivy-operator
    run_if_changed: "(pkg/ee/default-application-catalog/|.prow/)"
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubermatic.git"
    labels:
      preset-aws-e2e-kkp: "true"
      preset-kubeconfig-ci: "true"
      preset-docker-mirror: "true"
      preset-docker-pull: "true"
      preset-docker-push: "true"
      preset-kind-volume-mounts: "true"
      preset-goproxy: "true"
      preset-e2e-ssh: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.23-node-20-kind-0.24-4
          command:
            - "./hack/ci/run-default-application-e2e-test.sh"
          args:
            - "--application-name"
            - "trivy-operator"
          env:
            - name: KUBERMATIC_EDITION
              value: ee
            - name: SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: e2e-ci
                  key: serviceAccountSigningKey
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 14Gi
              cpu: 4
            limits:
              memory: 18Gi