presubmits:
  - name: pre-kubermatic-appcatalog-argocd
    run_if_changed: "(pkg/ee/default-application-catalog/argocd-app.yaml)"
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubermatic.git"
    labels:
      preset-aws-e2e-kkp: "true"
      preset-kubeconfig-ci: "true"
      preset-docker-mirror: "true"
      preset-docker-pull: "true"
      preset-docker-push: "true"
      preset-kind-volume-mounts: "true"
      preset-goproxy: "true"
      preset-e2e-ssh: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.23-node-20-kind-0.24-4
          command:
            - "./hack/ci/run-default-application-e2e-test.sh"
          args:
            - "--application-name"
            - "argocd"
            - "--application-version"
            - "v2.10.0"
          env:
            - name: KUBERMATIC_EDITION
              value: ee
            - name: SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: e2e-ci
                  key: serviceAccountSigningKey
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 14Gi
              cpu: 4
            limits:
              memory: 18Gi

  - name: pre-kubermatic-appcatalog-cert-manager
    run_if_changed: "(pkg/ee/default-application-catalog/cert-manager-app.yaml)"
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubermatic.git"
    labels:
      preset-aws-e2e-kkp: "true"
      preset-kubeconfig-ci: "true"
      preset-docker-mirror: "true"
      preset-docker-pull: "true"
      preset-docker-push: "true"
      preset-kind-volume-mounts: "true"
      preset-goproxy: "true"
      preset-e2e-ssh: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.23-node-20-kind-0.24-4
          command:
            - "./hack/ci/run-default-application-e2e-test.sh"
          args:
            - "--application-name"
            - "cert-manager"
            - "--application-version"
            - "v1.14.1"
          env:
            - name: KUBERMATIC_EDITION
              value: ee
            - name: SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: e2e-ci
                  key: serviceAccountSigningKey
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 14Gi
              cpu: 4
            limits:
              memory: 18Gi

  - name: pre-kubermatic-appcatalog-falco
    run_if_changed: "(pkg/ee/default-application-catalog/falco-app.yaml)"
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubermatic.git"
    labels:
      preset-aws-e2e-kkp: "true"
      preset-kubeconfig-ci: "true"
      preset-docker-mirror: "true"
      preset-docker-pull: "true"
      preset-docker-push: "true"
      preset-kind-volume-mounts: "true"
      preset-goproxy: "true"
      preset-e2e-ssh: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.23-node-20-kind-0.24-4
          command:
            - "./hack/ci/run-default-application-e2e-test.sh"
          args:
            - "--application-name"
            - "falco"
            - "--application-version"
            - "0.37.0"
          env:
            - name: KUBERMATIC_EDITION
              value: ee
            - name: SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: e2e-ci
                  key: serviceAccountSigningKey
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 14Gi
              cpu: 4
            limits:
              memory: 18Gi

  - name: pre-kubermatic-appcatalog-flux
    run_if_changed: "(pkg/ee/default-application-catalog/flux2-app.yaml)"
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubermatic.git"
    labels:
      preset-aws-e2e-kkp: "true"
      preset-kubeconfig-ci: "true"
      preset-docker-mirror: "true"
      preset-docker-pull: "true"
      preset-docker-push: "true"
      preset-kind-volume-mounts: "true"
      preset-goproxy: "true"
      preset-e2e-ssh: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.23-node-20-kind-0.24-4
          command:
            - "./hack/ci/run-default-application-e2e-test.sh"
          args:
            - "--application-name"
            - "flux"
            - "--application-version"
            - "2.2.2"
          env:
            - name: KUBERMATIC_EDITION
              value: ee
            - name: SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: e2e-ci
                  key: serviceAccountSigningKey
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 14Gi
              cpu: 4
            limits:
              memory: 18Gi

  - name: pre-kubermatic-appcatalog-k8sgpt
    run_if_changed: "(pkg/ee/default-application-catalog/k8sgpt-app.yaml)"
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubermatic.git"
    labels:
      preset-aws-e2e-kkp: "true"
      preset-kubeconfig-ci: "true"
      preset-docker-mirror: "true"
      preset-docker-pull: "true"
      preset-docker-push: "true"
      preset-kind-volume-mounts: "true"
      preset-goproxy: "true"
      preset-e2e-ssh: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.23-node-20-kind-0.24-4
          command:
            - "./hack/ci/run-default-application-e2e-test.sh"
          args:
            - "--application-name"
            - "k8sgpt"
            - "--application-version"
            - "v0.3.26"
          env:
            - name: KUBERMATIC_EDITION
              value: ee
            - name: SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: e2e-ci
                  key: serviceAccountSigningKey
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 14Gi
              cpu: 4
            limits:
              memory: 18Gi

  - name: pre-kubermatic-appcatalog-kube-vip
    run_if_changed: "(pkg/ee/default-application-catalog/kube-vip-app.yaml)"
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubermatic.git"
    labels:
      preset-aws-e2e-kkp: "true"
      preset-kubeconfig-ci: "true"
      preset-docker-mirror: "true"
      preset-docker-pull: "true"
      preset-docker-push: "true"
      preset-kind-volume-mounts: "true"
      preset-goproxy: "true"
      preset-e2e-ssh: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.23-node-20-kind-0.24-4
          command:
            - "./hack/ci/run-default-application-e2e-test.sh"
          args:
            - "--application-name"
            - "kube-vip"
            - "--application-version"
            - "v0.4.1"
          env:
            - name: KUBERMATIC_EDITION
              value: ee
            - name: SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: e2e-ci
                  key: serviceAccountSigningKey
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 14Gi
              cpu: 4
            limits:
              memory: 18Gi

  - name: pre-kubermatic-appcatalog-kubevirt
    run_if_changed: "(pkg/ee/default-application-catalog/kubevirt.yaml)"
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubermatic.git"
    labels:
      preset-aws-e2e-kkp: "true"
      preset-kubeconfig-ci: "true"
      preset-docker-mirror: "true"
      preset-docker-pull: "true"
      preset-docker-push: "true"
      preset-kind-volume-mounts: "true"
      preset-goproxy: "true"
      preset-e2e-ssh: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.23-node-20-kind-0.24-4
          command:
            - "./hack/ci/run-default-application-e2e-test.sh"
          args:
            - "--application-name"
            - "kubevirt"
            - "--application-version"
            - "v1.1.0"
          env:
            - name: KUBERMATIC_EDITION
              value: ee
            - name: SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: e2e-ci
                  key: serviceAccountSigningKey
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 14Gi
              cpu: 4
            limits:
              memory: 18Gi

  - name: pre-kubermatic-appcatalog-metallb
    run_if_changed: "(pkg/ee/default-application-catalog/metallb-app.yaml)"
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubermatic.git"
    labels:
      preset-aws-e2e-kkp: "true"
      preset-kubeconfig-ci: "true"
      preset-docker-mirror: "true"
      preset-docker-pull: "true"
      preset-docker-push: "true"
      preset-kind-volume-mounts: "true"
      preset-goproxy: "true"
      preset-e2e-ssh: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.23-node-20-kind-0.24-4
          command:
            - "./hack/ci/run-default-application-e2e-test.sh"
          args:
            - "--application-name"
            - "metallb"
            - "--application-version"
            - "v0.14.3"
          env:
            - name: KUBERMATIC_EDITION
              value: ee
            - name: SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: e2e-ci
                  key: serviceAccountSigningKey
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 14Gi
              cpu: 4
            limits:
              memory: 18Gi

  - name: pre-kubermatic-appcatalog-nginx-ingress-controller
    run_if_changed: "(pkg/ee/default-application-catalog/nginx-app.yaml)"
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubermatic.git"
    labels:
      preset-aws-e2e-kkp: "true"
      preset-kubeconfig-ci: "true"
      preset-docker-mirror: "true"
      preset-docker-pull: "true"
      preset-docker-push: "true"
      preset-kind-volume-mounts: "true"
      preset-goproxy: "true"
      preset-e2e-ssh: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.23-node-20-kind-0.24-4
          command:
            - "./hack/ci/run-default-application-e2e-test.sh"
          args:
            - "--application-name"
            - "nginx_ingress_controller"
            - "--application-version"
            - "1.9.6"
          env:
            - name: KUBERMATIC_EDITION
              value: ee
            - name: SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: e2e-ci
                  key: serviceAccountSigningKey
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 14Gi
              cpu: 4
            limits:
              memory: 18Gi

  - name: pre-kubermatic-appcatalog-nvidia-gpu-operator
    run_if_changed: "(pkg/ee/default-application-catalog/nvidia-gpu-operator-app.yaml)"
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubermatic.git"
    labels:
      preset-aws-e2e-kkp: "true"
      preset-kubeconfig-ci: "true"
      preset-docker-mirror: "true"
      preset-docker-pull: "true"
      preset-docker-push: "true"
      preset-kind-volume-mounts: "true"
      preset-goproxy: "true"
      preset-e2e-ssh: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.23-node-20-kind-0.24-4
          command:
            - "./hack/ci/run-default-application-e2e-test.sh"
          args:
            - "--application-name"
            - "nvidia_gpu_operator"
            - "--application-version"
            - "v23.9.1"
          env:
            - name: KUBERMATIC_EDITION
              value: ee
            - name: SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: e2e-ci
                  key: serviceAccountSigningKey
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 14Gi
              cpu: 4
            limits:
              memory: 18Gi

  - name: pre-kubermatic-appcatalog-trivy
    run_if_changed: "(pkg/ee/default-application-catalog/trivy-app.yaml)"
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubermatic.git"
    labels:
      preset-aws-e2e-kkp: "true"
      preset-kubeconfig-ci: "true"
      preset-docker-mirror: "true"
      preset-docker-pull: "true"
      preset-docker-push: "true"
      preset-kind-volume-mounts: "true"
      preset-goproxy: "true"
      preset-e2e-ssh: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.23-node-20-kind-0.24-4
          command:
            - "./hack/ci/run-default-application-e2e-test.sh"
          args:
            - "--application-name"
            - "trivy"
            - "--application-version"
            - "0.37.2"
          env:
            - name: KUBERMATIC_EDITION
              value: ee
            - name: SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: e2e-ci
                  key: serviceAccountSigningKey
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 14Gi
              cpu: 4
            limits:
              memory: 18Gi

  - name: pre-kubermatic-appcatalog-trivy-operator
    run_if_changed: "(pkg/ee/default-application-catalog/trivy-operator-app.yaml"
    decorate: true
    clone_uri: "ssh://git@github.com/kubermatic/kubermatic.git"
    labels:
      preset-aws-e2e-kkp: "true"
      preset-kubeconfig-ci: "true"
      preset-docker-mirror: "true"
      preset-docker-pull: "true"
      preset-docker-push: "true"
      preset-kind-volume-mounts: "true"
      preset-goproxy: "true"
      preset-e2e-ssh: "true"
    spec:
      containers:
        - image: quay.io/kubermatic/build:go-1.23-node-20-kind-0.24-4
          command:
            - "./hack/ci/run-default-application-e2e-test.sh"
          args:
            - "--application-name"
            - "trivy-operator"
            - "--application-version"
            - "0.18.4"
          env:
            - name: KUBERMATIC_EDITION
              value: ee
            - name: SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: e2e-ci
                  key: serviceAccountSigningKey
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 14Gi
              cpu: 4
            limits:
              memory: 18Gi